services:
  task-runners:
    image: ghcr.io/uwcirg/n8n-builder:${RUNNERS_IMAGE_TAG:-runner-main}
    restart: unless-stopped
    volumes:
      - ./n8n-task-runners.json:/etc/n8n-task-runners.json:ro
