services:
  jupyterhub:
    image: jupyterhub/jupyterhub:latest
    restart: unless-stopped
    command:
      - jupyterhub
      - -f
      - /srv/jupyterhub/jupyterhub_config.py
    expose:
      - 8000
    volumes:
      - jupyterhub_data:/srv/jupyterhub
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro

volumes:
  jupyterhub_data:

networks:
  internal:
  # ingress network
  ingress:
    external: true
    name: external_web
